import { type Chapter } from '../journey/types';

export const HARD_DISK_CHAPTERS: Chapter[] = [
  {
    id: 'materials',
    number: 1,
    title: 'Raw Materials',
    subtitle: 'Mining the magnetic age',
    hook: 'The memory of your photos is held by rare earth metals mined from the depths of the Earth.',
    color: '#3b82f6',
    body: [
      'A hard disk drive (HDD) is a symphony of metals. The most critical are Neodymium, Iron, and Boron. Together, they form Neodymium magnets (NdFeB) — the strongest permanent magnets commercially available. These are used in the read/write actuator arm. Neodymium is a "rare earth" element, predominantly mined and processed in China, which controls over 60% of the world\'s rare earth production.',
      'The platters — the disks that actually hold your data — are typically made of an aluminum alloy or, in high-capacity drives, glass or ceramic substrates. Aluminum comes from bauxite ore, extensively mined in Australia and Guinea. Glass platters offer better rigidity at high speeds (up to 15,000 RPM) and can be made thinner, allowing more platters per drive.',
      'The platters are sputtered with extremely thin layers of magnetic material, primarily a Cobalt alloy (Cobalt-Platinum-Chromium). Platinum and Chromium are crucial for stabilizing the magnetic domains so your data doesn\'t degrade over time.',
      'Finally, Gold and Copper are essential. Gold is used on the printed circuit board (PCB) contacts because it never corrodes, ensuring perfect electrical connections over the drive\'s lifespan. Copper is wound into the voice coil motor that rapidly snaps the actuator arm back and forth across the platters.'
    ],
    facts: [
      { label: 'Neodymium production', value: '>60%', unit: 'mined in China' },
      { label: 'Platter substrate', value: 'Alum / Glass', unit: 'for high rigidity' },
      { label: 'Magnetic film thickness', value: '10–20', unit: 'nanometers' },
      { label: 'Key magnetic alloy', value: 'Co-Pt-Cr', unit: 'Cobalt-Platinum-Chromium' },
      { label: 'Gold plating', value: '0.05', unit: 'microns thick on contacts' }
    ],
    mapPoints: [
      { country: 'China', material: 'Neodymium', role: 'Actuator magnets', coords: { x: 72, y: 35 } },
      { country: 'Australia', material: 'Bauxite', role: 'Aluminum platters', coords: { x: 80, y: 65 } },
      { country: 'South Africa', material: 'Platinum', role: 'Magnetic coating', coords: { x: 55, y: 75 } },
      { country: 'Congo', material: 'Cobalt', role: 'Magnetic coating', coords: { x: 53, y: 60 } }
    ],
    pullQuote: 'To store your digital memories in the cloud, we must first extract Neodymium, Platinum, and Cobalt from the earth.',
    timeline: [
      { year: '1980s', event: 'Neodymium magnets invented, enabling dramatic miniaturization of HDDs' },
      { year: '1990s', event: 'Transition from aluminum to glass platters begins for laptop drives' },
      { year: '2010s', event: 'Rare earth supply chain crisis highlights dependence on Chinese Neodymium' }
    ]
  },
  {
    id: 'manufacturing',
    number: 2,
    title: 'Manufacturing',
    subtitle: 'The cleanest rooms on Earth',
    hook: 'A single speck of dust dropping onto an HDD platter is like a boulder crashing into a highway.',
    color: '#0ea5e9',
    body: [
      'Hard drives must be assembled in Class 100 cleanrooms — environments with fewer than 100 particles larger than 0.5 microns per cubic foot of air. For comparison, a typical hospital operating room is about a Class 10,000 cleanroom. A single human hair is roughly 75 microns wide; a speck of dust is around 10 microns.',
      'Why such extreme cleanliness? The read/write head of a hard drive "flies" above the spinning platter on a cushion of air generated by the platter\'s rotation. The gap between the head and the platter is approximately 2 to 5 nanometers. A DNA strand is 2.5 nanometers wide. A single fingerprint smudge or dust particle is massive enough to crash the head into the platter, permanently destroying data.',
      'The read/write heads maintain a flying height of just 10 angstroms above the spinning platter. To visualize that precision, it is a gap equivalent to the width of just two water molecules. These heads fly over data tracks with a precision of less than 2 nanometers, moving at speeds equivalent to a car traveling 80 mph without drifting more than 10 atoms to either side.',
      "The spinning surface below the head contains nearly 800,000 tracks, each one 2,500 times thinner than a human hair. A single bit of information races by every nanosecond. Because the tolerances are so tight, the majority of the manufacturing and operation must be handled by 'nano-robotics' and custom algorithms orchestrated by nanoscale chips. This level of post-nano engineering allows 4 billion bits of information to be perfectly decoded every single second.",
      'The platters are manufactured using magnetron sputtering. In a vacuum chamber, argon gas is ionized to blast atoms of cobalt and platinum off a target, depositing them onto the platter one atomic layer at a time. This process creates the incredibly uniform magnetic layer needed to store terabytes of data.',
      'High-capacity drives manufactured today are frequently filled with Helium instead of air. Helium is one-seventh the density of air. This reduces aerodynamic drag, allowing the platters to spin with less power and creating less turbulence, which allows the platters to be stacked closer together. The drives are hermetically sealed by laser-welding the aluminum casing to trap the helium inside down to the atomic level. Even a tiny leak would allow the helium to escape over time, degrading performance. The manufacturing process includes rigorous helium leak testing, using mass spectrometry to detect leaks as small as 1x10^-9 mbar·L/s.'
    ],
    facts: [
      { label: 'Cleanroom Class', value: '100', unit: 'particles per cubic foot' },
      { label: 'Head flying height', value: '2–5 nm', unit: 'thinner than a virus' },
      { label: 'Sputtering process', value: 'Atomic', unit: 'layer deposition' },
      { label: 'Helium density', value: '1/7th', unit: 'density of air' },
      { label: 'Casing seal', value: 'Laser-welded', unit: 'to prevent helium escape' }
    ],
    pullQuote: 'The read/write head flies above the platter at a height equivalent to a Boeing 747 flying a few millimeters above the ground.',
    timeline: [
      { year: '1956', event: 'IBM RAMAC introduces the first HDD. It required an air compressor to keep the heads floating' },
      { year: '1973', event: 'IBM "Winchester" drive reduces flying height to 17 microinches, sealing the drive from outside air' },
      { year: '2013', event: 'HGST releases the first mass-produced Helium-filled hard drive' }
    ]
  },
  {
    id: 'supply-chain',
    number: 3,
    title: 'Supply Chain',
    subtitle: 'Moving fragile perfection',
    hook: 'Transporting an unassembled hard drive across the ocean is harder than transporting explosives.',
    color: '#3b82f6',
    body: [
      'Hard disk drives are assembled mainly in Southeast Asia — particularly Thailand, Malaysia, and China. This regional concentration relies on highly specialized local supply ecosystems. Platter manufacturers, motor assemblies, and PCB fab plants are tightly clustered to minimize transit times and costs.',
      'The fragility of the components makes the supply chain incredibly tricky. Parts must be shipped in electrostatic discharge (ESD) safe, shock-absorbent packaging. Sudden impacts during transit can misalign the microscopic read/write heads before they are even installed.',
      'In 2011, severe flooding in Thailand submerged major industrial estates. Thailand accounted for nearly 30% of the world\'s hard drive production at the time. Factories operated by Western Digital and Toshiba, as well as crucial motor suppliers like Nidec, were completely submerged. Global HDD production fell by 30%, prices doubled, and it took the industry years to recover.',
      'Today, the supply chain for HDDs is shifting again. Assembly is consolidating into fewer, massive "mega-factories." The major buyers of these drives are no longer individual consumers buying PCs, but hyperscale cloud providers — Amazon, Google, and Microsoft — who purchase millions of drives a year to build massive data centers.'
    ],
    facts: [
      { label: 'Thailand global share', value: '~30%', unit: 'of HDD production (historical peak)' },
      { label: 'Major assembly hubs', value: 'SE Asia', unit: 'Thailand, Malaysia, China' },
      { label: '2011 Flood impact', value: '-30%', unit: 'drop in global supply' },
      { label: 'Largest buyers', value: 'Hyperscalers', unit: 'AWS, Google, Microsoft' }
    ],
    pullQuote: 'A flood in Thailand in 2011 doubled the price of computer storage worldwide overnight.',
    timeline: [
      { year: '1990s', event: 'HDD manufacturing begins shifting heavily to Southeast Asia for lower costs' },
      { year: '2011', event: 'Thai floods devastate the global HDD supply chain' },
      { year: '2020s', event: 'Enterprise datacenters become the primary destination for all high-capacity HDDs' }
    ]
  },
  {
    id: 'science',
    number: 4,
    title: 'Science & Engineering',
    subtitle: 'Quantum physics in a metal box',
    hook: 'The hard drive is the most successful application of nanotechnology in human history.',
    color: '#0ea5e9',
    body: [
      "As we shrink bits to increase capacity, recording material becomes magnetically unstable at nanoscale dimensions. To solve this, scientists developed a groundbreaking 'super-lattice' structure for the storage layer, where every single atom is set exactly into place to provide the high magnetic coercivity required for stable data.",
      'At its core, a hard disk stores data by magnetizing billions of microscopic regions on the platter. A traditional drive lays these magnetic regions side-by-side horizontally. However, as drives grew denser, the magnetic regions became so small that ambient room temperature could cause them to randomly flip their magnetic state, destroying the data (the "superparamagnetic limit").',
      'Engineers solved this by standing the magnets up vertically — Perpendicular Magnetic Recording (PMR) — introduced in 2005. This allowed data density to leap forward.',
      'Reading these incredibly tiny magnetic fields required a Nobel Prize-winning discovery. In 2007, Albert Fert and Peter Grünberg won the Nobel Prize in Physics for discovering Giant Magnetoresistance (GMR). The GMR effect uses quantum mechanics: a structure made of incredibly thin alternating magnetic and non-magnetic layers changes its electrical resistance wildly in the presence of a tiny magnetic field. This quantum effect is what allows the read head to detect your data on the platter.',
      "To push capacities even higher, modern drives use Energy-Assisted Magnetic Recording (EAMR), such as HAMR (Heat-Assisted Magnetic Recording). HAMR uses a microscopic laser (a 'plasmonic transducer'—a 3D nanoscale structure that guides light to generate an electric field, heating an area no bigger than a single bit) mounted on the read/write head to briefly heat a 20-nanometer spot on the platter to 400°C for one nanosecond, writing the data, and letting it cool instantly. This enables multi-terabyte drives in the data centers that host the modern internet.",
      "The 'brains' managing this dialogue consist of millions of lines of code running on cutting-edge nanoscale chips. These processors use complex hardware logic and custom algorithms to orchestrate the movement of data in trillionths of a second (picoseconds), making the invisible infrastructure of the digital world possible."
    ],
    facts: [
      { label: 'Superparamagnetic limit', value: 'The wall', unit: 'where thermal energy destroys data' },
      { label: 'GMR Effect', value: 'Quantum', unit: 'mechanics used for the read head' },
      { label: 'HAMR Laser Heating', value: '400°C', unit: 'for a single nanosecond' },
      { label: 'Data density', value: '>1 Tb', unit: 'per square inch of platter' }
    ],
    pullQuote: 'Your hard drive relies on quantum mechanics and nanoscale lasers firing for a nanosecond at 400°C.',
    timeline: [
      { year: '1997', event: 'IBM introduces GMR heads, massively increasing storage density' },
      { year: '2005', event: 'Perpendicular Magnetic Recording (PMR) begins shipping to combat the superparamagnetic limit' },
      { year: '2007', event: 'Nobel Prize in Physics awarded for the discovery of Giant Magnetoresistance (GMR)' },
      { year: '2020s', event: 'HAMR (Heat-Assisted Magnetic Recording) drives enter commercial use' }
    ]
  },
  {
    id: 'economics',
    number: 5,
    title: 'Economics & Business',
    subtitle: 'The race to the bottom of the cloud',
    hook: 'The storage paradox: making it cheaper makes us want infinitely more of it.',
    color: '#3b82f6',
    body: [
      'In 1956, storing 5 megabytes of data — roughly one MP3 song today — cost $3,200 per month to rent from IBM. Today, a 20 Terabyte hard drive costs around $300. The cost per gigabyte of hard drive storage has fallen exponentially for over forty years, a trend affectionately called "Kryder\'s Law" (the storage equivalent of Moore\'s Law).',
      'Despite the rise of Solid State Drives (SSDs), hard disks are far from dead. SSDs are much faster, meaning they have taken over the consumer laptop and smartphone market almost entirely. But SSD flash memory is still roughly 5 times more expensive per gigabyte than spinning hard disks.',
      'Because of this cost canyon, the vast majority of "The Cloud" lives on spinning hard disks. When you upload a video to YouTube, stream a movie on Netflix, or backup your phone to iCloud, that data is almost certainly resting on a magnetic platter inside a data center.',
      'The HDD industry has heavily consolidated to survive. There were over 70 hard drive manufacturers in the 1980s. Today, only three major companies remain: Western Digital, Seagate, and Toshiba. They operate in a razor-thin margin environment, surviving by shipping Exabytes (billions of gigabytes) of storage to a handful of hyper-scale tech giants.'
    ],
    facts: [
      { label: 'Cost of 1 GB (1981)', value: '$500,000', unit: 'approximate equivalent' },
      { label: 'Cost of 1 GB (2025)', value: '<$0.015', unit: 'for high-capacity drives' },
      { label: 'Remaining manufacturers', value: '3', unit: 'down from 70+ in the 1980s' },
      { label: 'HDD vs SSD Cost', value: '~5x', unit: 'HDDs remain drastically cheaper for bulk data' }
    ],
    pullQuote: 'The "cloud" isn\'t a fluffy ethereal place. It is enormous warehouses filled with millions of spinning magnetic platters.',
    timeline: [
      { year: '1956', event: 'IBM RAMAC leased for $3,200 a month for 5 Megabytes' },
      { year: '1980', event: 'Seagate completely changes personal computing by introducing the first 5.25-inch HDD for microcomputers' },
      { year: '2010s', event: 'Industry consolidation occurs. Maxtor, HGST, Samsung, and others are acquired' },
      { year: '2023', event: 'Over 1,000 Exabytes of HDD storage shipped globally in a single year' }
    ]
  },
  {
    id: 'legal',
    number: 6,
    title: 'Laws & E-Waste',
    subtitle: 'The afterlife of your data',
    hook: 'Destroying a hard drive physically is often legally required, leaving toxic metals behind.',
    color: '#0ea5e9',
    body: [
      'The laws governing data privacy intensely impact the physical fate of hard drives. Regulations like HIPAA (healthcare), SOX (finance), and GDPR (privacy) require companies to guarantee that sensitive data is destroyed when old servers are decommissioned.',
      'Software wiping is slow and sometimes fallible. As a result, companies routinely use industrial shredders to physically destroy functional hard drives rather than risk a data leak. This practice ensures data security but creates a massive e-waste problem.',
      'Hard drives contain highly recyclable and valuable materials: aluminum, rare earth magnets, and gold. However, when an HDD is shredded for data security, these materials are mixed together into a difficult-to-separate metallic gravel. Extracting the Neodymium from shredded drives is currently not economically viable at scale.',
      'Global e-waste regulations, such as the EU\'s WEEE Directive, heavily regulate how these crushed electronics are processed. But a significant portion of the world\'s e-waste is still illegally shipped to developing nations, where informal workers burn away plastics to scavenge the remaining copper and gold, creating toxic environmental hazards.',
      'A new wave of circular economy initiatives is trying to mandate better recycling paths for cloud infrastructure, pushing for robotic disassembly of hard drives to recover the intact rare-earth magnets before the rest of the casing is shredded.'
    ],
    facts: [
      { label: 'Primary shredding reason', value: 'Compliance', unit: 'HIPAA, GDPR security requirements' },
      { label: 'Rare earth recovery', value: '<5%', unit: 'of neodymium is currently recycled globally' },
      { label: 'Data eradication standard', value: 'NIST 800-88', unit: 'U.S. standard for media sanitation' },
      { label: 'E-Waste regulation', value: 'WEEE', unit: 'EU directive on electronic waste' }
    ],
    pullQuote: 'In the name of data privacy, we put functioning drives into industrial shredders, turning rare earth elements into irrecoverable dust.',
    timeline: [
      { year: '1996', event: 'HIPAA enacted in the U.S., increasing the need for physical data destruction protocols' },
      { year: '2003', event: 'EU\'s WEEE Directive takes effect, mandating electronics recycling and holding manufacturers responsible' },
      { year: '2018', event: 'GDPR implemented, levying massive fines for data leaks, further driving physical destruction of IT assets' },
      { year: '2020s', event: 'Apple, Google, and others begin pilot programs to robotically recover rare earth magnets from old HDDs' }
    ]
  }
];
