import { type Chapter } from '../journey/types';

export const PEN_CHAPTERS: Chapter[] = [
  {
    id: 'materials',
    number: 1,
    title: 'Raw Materials',
    subtitle: 'Where the world is mined',
    hook: 'Your pen is a world tour in your pocket.',
    color: '#c9933a',
    body: [
      'Before a single pen is assembled, its components have already crossed oceans. The ballpoint tip — that tiny sphere you press to paper — is made of tungsten carbide, one of the hardest materials on Earth. Tungsten is mined primarily in China, which controls over 80% of global supply. The carbide is formed by combining tungsten with carbon at temperatures exceeding 1,400°C.',
      'The brass housing that holds the tip is an alloy of copper and zinc. Copper comes largely from Chile and Peru — the Atacama Desert, one of the driest places on Earth, sits atop some of the world\'s richest copper deposits. Zinc is often sourced from Australia, China, or Peru.',
      'The ink itself is a carefully engineered mixture. Ballpoint ink is oil-based — a blend of dyes or pigments, fatty acids, and resins dissolved in solvents like phenoxyethanol. The dye chemistry traces back to synthetic aniline dyes first developed in Germany in the 1850s. The resin binders are derived from petroleum, which means your pen\'s ink has a lineage stretching back to ancient organic matter compressed over millions of years.',
      'The plastic barrel — typically polypropylene or polystyrene — is a petroleum derivative. Crude oil is extracted, refined, cracked into ethylene or propylene, and polymerized into pellets before being injection-molded into the barrel shape you hold.',
      'Even the small spring inside a retractable pen is a precision-formed stainless steel coil, likely sourced from steel mills in South Korea, Japan, or Germany.',
    ],
    facts: [
      { label: 'Tungsten carbide hardness', value: '9.5', unit: 'Mohs scale (diamond is 10)' },
      { label: 'China\'s share of global tungsten supply', value: '82%', unit: 'of world production' },
      { label: 'Tip ball diameter', value: '0.7–1mm', unit: 'typical ballpoint' },
      { label: 'Countries contributing materials', value: '6+', unit: 'continents represented' },
      { label: 'Ink components', value: '20–30', unit: 'distinct chemical compounds' },
    ],
    mapPoints: [
      { country: 'China', material: 'Tungsten', role: 'Tip material', coords: { x: 72, y: 35 } },
      { country: 'Chile', material: 'Copper', role: 'Brass housing', coords: { x: 28, y: 68 } },
      { country: 'Australia', material: 'Zinc', role: 'Brass alloy', coords: { x: 80, y: 65 } },
      { country: 'Saudi Arabia', material: 'Crude Oil', role: 'Ink & plastic', coords: { x: 57, y: 38 } },
      { country: 'Germany', material: 'Dye chemistry', role: 'Ink pigments', coords: { x: 49, y: 26 } },
      { country: 'South Korea', material: 'Steel', role: 'Spring & machinery', coords: { x: 76, y: 32 } },
    ],
    pullQuote: 'The tungsten carbide tip travels across three continents before it ever touches paper.',
    timeline: [
      { year: '1850s', event: 'Synthetic aniline dyes invented in Germany — the chemistry behind pen ink begins' },
      { year: '1888', event: 'John Loud patents the first ballpoint pen concept, using a rotating steel ball' },
      { year: '1938', event: 'László Bíró patents the modern ballpoint pen with oil-based ink in Hungary' },
      { year: '1945', event: 'Bíró pens sold to RAF pilots — first mass use case (ink works at altitude)' },
      { year: '1960s', event: 'Tungsten carbide replaces steel for the tip ball — durability increases 10x' },
    ],
  },
  {
    id: 'manufacturing',
    number: 2,
    title: 'Manufacturing',
    subtitle: 'The machines behind the mundane',
    hook: 'The machine that makes your pen costs more than a house.',
    color: '#a0522d',
    body: [
      'The ballpoint tip is the most precisely engineered component in your pen — and one of the most precisely engineered objects in everyday life. The tungsten carbide ball must be a near-perfect sphere, ground to tolerances of ±0.001mm (one micron). For context, a human hair is about 70 microns wide. The socket that holds the ball must be machined to allow the ball to rotate freely while preventing ink from leaking — a gap of just a few microns.',
      'This precision is achieved on CNC (Computer Numerical Control) lathes and grinding machines that run 24 hours a day. A single tip-manufacturing machine costs upward of $500,000. The factories that make ballpoint tips are highly specialized — there are only a handful in the world capable of this level of precision at scale.',
      'The plastic barrel is made by injection molding. Plastic pellets (polypropylene) are heated to ~230°C until molten, then injected under high pressure into a steel mold. The mold itself — precision-machined from hardened tool steel — costs $50,000–$150,000 and can produce millions of barrels before wearing out.',
      'The ink is manufactured in separate chemical plants, mixed in large batches, and tested for viscosity, color consistency, and flow rate. Ballpoint ink must have a very specific viscosity — roughly 10,000 times thicker than water — so it flows only when the ball rotates under writing pressure, not from gravity alone.',
      'Final assembly is almost entirely automated. Robotic arms insert the ink cartridge, press in the tip, attach the spring and click mechanism, and snap on the cap — all at rates of hundreds of pens per minute. Quality control uses optical sensors to reject any pen where the tip isn\'t seated correctly.',
    ],
    facts: [
      { label: 'Tip ball tolerance', value: '±0.001mm', unit: '1 micron — 70x thinner than a hair' },
      { label: 'Tip-making machine cost', value: '$500K+', unit: 'per unit' },
      { label: 'Injection mold cost', value: '$50K–$150K', unit: 'per barrel mold' },
      { label: 'Ink viscosity vs water', value: '10,000x', unit: 'thicker' },
      { label: 'Assembly speed', value: '400+', unit: 'pens per minute (automated)' },
    ],
    pullQuote: 'A human hair is 70 microns wide. The gap between the tip ball and its socket is measured in single microns.',
    timeline: [
      { year: '1945', event: 'First commercial ballpoint pens hand-assembled — expensive and unreliable' },
      { year: '1950s', event: 'Frito-Lay engineer Marcel Bich licenses Bíró\'s patent, industrializes production — BIC born' },
      { year: '1960', event: 'BIC Cristal launched — first truly mass-produced disposable pen at scale' },
      { year: '1970s', event: 'CNC machining introduced to tip manufacturing — tolerances tighten dramatically' },
      { year: '1990s', event: 'Fully automated assembly lines replace most manual labor in pen factories' },
      { year: '2000s', event: 'Optical quality control systems introduced — near-zero defect rates achieved' },
    ],
  },
  {
    id: 'supply-chain',
    number: 3,
    title: 'Supply Chain',
    subtitle: 'The invisible web that delivers your pen',
    hook: 'A disruption in one Chilean mine can delay pen production on three continents.',
    color: '#c9933a',
    body: [
      'The global supply chain for a ballpoint pen involves dozens of companies across multiple continents, coordinated by contracts, shipping schedules, and just-in-time inventory systems that leave almost no margin for error.',
      'Raw materials are extracted and processed in their source countries, then shipped — often in bulk cargo vessels — to processing facilities. Copper from Chile travels to smelters, then to brass mills, then to tip manufacturers. Each step adds cost, time, and logistical complexity.',
      'The pen industry relies heavily on container shipping. A standard 20-foot shipping container holds roughly 5 million pens. The global shipping network — about 50,000 merchant vessels — moves 90% of world trade. When the Ever Given blocked the Suez Canal for six days in 2021, it disrupted supply chains for everything from electronics to stationery.',
      'Just-in-time (JIT) manufacturing, pioneered by Toyota, means pen factories hold minimal inventory. Components arrive from suppliers precisely when needed. This reduces storage costs but creates fragility — a single supplier delay can halt an entire production line.',
      'The final pen travels from factory (often in China, Japan, or Mexico) to regional distribution centers, then to retailers, then to you. A pen manufactured in Shenzhen might pass through 8–12 different companies\' hands before reaching a shelf in Mumbai or Chicago.',
    ],
    facts: [
      { label: 'Companies in a pen\'s supply chain', value: '20–50', unit: 'direct and indirect' },
      { label: 'Pens per shipping container', value: '~5 million', unit: '20-foot container' },
      { label: 'Share of world trade by sea', value: '90%', unit: 'by volume' },
      { label: 'Typical supply chain length', value: '8–12', unit: 'company handoffs' },
      { label: 'Countries in supply chain', value: '10+', unit: 'for a single pen model' },
    ],
    pullQuote: 'The pen in your hand has been touched — indirectly — by thousands of workers on six continents.',
    timeline: [
      { year: '1956', event: 'Standardized shipping containers invented by Malcolm McLean — global trade transforms' },
      { year: '1970s', event: 'Toyota\'s just-in-time manufacturing spreads globally — pen factories adopt lean supply chains' },
      { year: '1990s', event: 'China becomes dominant pen manufacturer — global supply chains restructure around Chinese factories' },
      { year: '2001', event: 'China joins WTO — pen imports/exports accelerate dramatically' },
      { year: '2020', event: 'COVID-19 disrupts global supply chains — pen shortages reported in some markets' },
      { year: '2021', event: 'Ever Given blocks Suez Canal — illustrates fragility of global shipping networks' },
    ],
  },
  {
    id: 'science',
    number: 4,
    title: 'Science & Engineering',
    subtitle: 'Decades of chemistry and physics in your grip',
    hook: 'Getting ink to flow only when you want it to took 20 years of failure.',
    color: '#c9933a',
    body: [
      'The ballpoint pen seems simple. It isn\'t. The core engineering challenge — getting ink to flow smoothly onto paper under writing pressure, but not leak or dry out otherwise — took decades to solve and involves surprisingly deep physics and chemistry.',
      'Early ballpoint pens (1940s) were notorious for leaking, skipping, and blotting. The problem was ink viscosity. Water-based inks (like fountain pen ink) are too thin — they leak around the ball. The solution was oil-based ink, but oil-based inks are thick and resist flow. The ball must rotate under the friction of writing, drawing ink from the reservoir through capillary action and depositing it on paper.',
      'The ink must also dry almost instantly on contact with paper (oxidative polymerization — the resins in the ink react with oxygen to harden) but remain fluid in the sealed reservoir. This requires a precise balance of solvents, resins, and drying agents.',
      'The tip geometry is a marvel of miniature engineering. The ball sits in a socket with a tiny gap — large enough for ink to flow through, small enough to prevent leakage. The socket has tiny channels machined into it to distribute ink evenly around the ball. Getting this geometry right required iterative testing across thousands of prototypes.',
      'Modern gel pens introduced a different chemistry: water-based ink thickened with a polymer gel (typically xanthan gum or a synthetic equivalent). Gel ink flows more smoothly and produces more vivid colors, but requires even tighter tip tolerances to prevent leaking.',
      'The plastic barrel must be chemically inert — it cannot react with the ink over years of storage. Polypropylene was chosen partly because it resists the solvents in ballpoint ink. The transparent window in many pens (to see ink level) uses a different, clearer plastic that must also be chemically compatible.',
    ],
    facts: [
      { label: 'Years to perfect ballpoint ink', value: '~20', unit: 'from 1938 to reliable commercial product' },
      { label: 'Ink drying mechanism', value: 'Oxidative', unit: 'polymerization on paper contact' },
      { label: 'Ball rotation speed', value: '~600 RPM', unit: 'at normal writing speed' },
      { label: 'Ink reservoir pressure', value: 'Atmospheric', unit: 'carefully balanced to prevent leaking' },
      { label: 'Gel ink polymer', value: 'Xanthan gum', unit: 'same thickener used in salad dressing' },
    ],
    pullQuote: 'The same polymer chemistry that makes your pen ink dry on paper is used in industrial coatings and varnishes.',
    timeline: [
      { year: '1938', event: 'László Bíró patents oil-based ballpoint ink — solves the leaking problem in theory' },
      { year: '1945', event: 'First commercial pens still leak and skip — ink chemistry still imperfect' },
      { year: '1950s', event: 'Parker and Waterman invest heavily in ink chemistry — viscosity formulas refined' },
      { year: '1960s', event: 'Paul Fisher develops pressurized ink cartridge for NASA — works in zero gravity' },
      { year: '1984', event: 'Sakura Color Products invents gel ink pen — new chemistry, smoother writing' },
      { year: '2000s', event: 'Hybrid inks developed — combine oil and water-based chemistry for best of both' },
    ],
  },
  {
    id: 'economics',
    number: 5,
    title: 'Economics & Business',
    subtitle: 'Billions made from fractions of a cent',
    hook: 'The pen industry is worth $18 billion. The pen costs $0.10. Do the math.',
    color: '#a0522d',
    body: [
      'The economics of the pen industry are a masterclass in scale. A basic ballpoint pen retails for $0.10–$0.50. The raw material cost is perhaps $0.02–$0.05. The manufacturing cost (labor, energy, machine depreciation) adds another $0.01–$0.03. Shipping, distribution, and retail markup account for the rest.',
      'BIC — the world\'s largest pen manufacturer — sells approximately 57 pens per second globally. Their Cristal pen, launched in 1950, has sold over 100 billion units. At $0.10 each, that\'s $10 billion from a single product. The company\'s entire value is built on mastering the economics of extreme volume and minimal margin.',
      'The pen industry is highly consolidated at the top. BIC, Pilot, Zebra, Pentel, and Staedtler control a large share of the global market. But beneath them is a vast ecosystem of smaller manufacturers — particularly in China — producing unbranded pens for private-label retailers, schools, and offices worldwide.',
      'The real money in pens isn\'t in the cheap ballpoints — it\'s in premium writing instruments. Montblanc\'s Meisterstück pen sells for $700–$1,000. The materials cost is perhaps $50. The rest is brand, craftsmanship, and the psychology of luxury. The same basic technology — ink + ball + barrel — spans a 10,000x price range.',
      'Pen companies also profit from the "razor and blades" model: sell the pen cheaply, profit from refills. Parker and Cross built entire business models around premium pens with proprietary refill cartridges. The refill business has higher margins and creates customer lock-in.',
    ],
    facts: [
      { label: 'Global pen market value', value: '$18B', unit: 'annually' },
      { label: 'BIC Cristal units sold', value: '100B+', unit: 'since 1950' },
      { label: 'BIC pens sold per second', value: '57', unit: 'globally' },
      { label: 'Cheapest pen retail price', value: '$0.03', unit: 'bulk unbranded' },
      { label: 'Most expensive pen', value: '$1.47M', unit: 'Aurora Diamante (diamond-encrusted)' },
    ],
    pullQuote: 'BIC sells 57 pens every second. Their entire empire is built on mastering fractions of a cent.',
    timeline: [
      { year: '1945', event: 'First ballpoint pens sell for $12.50 each — equivalent to ~$200 today' },
      { year: '1950', event: 'Marcel Bich launches BIC Cristal at 29 cents — democratizes the ballpoint pen' },
      { year: '1960s', event: 'Price wars drive ballpoint pens below $1 — fountain pen industry collapses' },
      { year: '1970s', event: 'Disposable pen becomes global norm — billions sold annually' },
      { year: '1990s', event: 'Chinese manufacturers enter market — prices fall further, margins compress' },
      { year: '2010s', event: 'Premium pen revival — Kickstarter campaigns raise millions for "artisan" pens' },
    ],
  },
  {
    id: 'legal',
    number: 6,
    title: 'Laws & Regulations',
    subtitle: 'The invisible rules that shaped your pen',
    hook: 'A 30% tariff once decided which country would dominate the global pen industry.',
    color: '#c9933a',
    body: [
      'The pen you hold is shaped not just by engineering and economics, but by law. Patents, trade tariffs, safety regulations, and intellectual property disputes have redirected the pen industry multiple times throughout history.',
      'László Bíró\'s original ballpoint patent was licensed, sold, and contested across multiple countries. When he sold the rights to different companies in different territories, it created a fragmented patent landscape that shaped which companies could manufacture pens where. The US market was dominated by different players than Europe, partly due to patent geography.',
      'Trade tariffs have been decisive. In the 1960s and 70s, the US imposed tariffs on imported pens to protect domestic manufacturers. This forced foreign companies to either build US factories or accept reduced market access. Similar dynamics played out in India, Brazil, and other developing markets — local pen industries were built behind tariff walls.',
      'Safety regulations govern what can go into pen ink. The FDA regulates inks used in pens that might contact food or be used by children. The EU\'s REACH regulation restricts certain chemicals in consumer products, including pen inks. Phthalates (used as plasticizers in some pen barrels) are now restricted in children\'s products in many countries.',
      'Intellectual property battles have been fierce. Pilot sued Pentel over gel ink technology. BIC has defended its trademark against countless imitators. The design of the BIC Cristal — its hexagonal barrel, transparent body — is now protected as a design trademark in many countries.',
      'Environmental regulations are increasingly shaping pen design. The EU\'s Single-Use Plastics Directive has pushed manufacturers toward refillable designs. California\'s Proposition 65 requires warnings on products containing certain chemicals, affecting which pen formulations can be sold there.',
    ],
    facts: [
      { label: 'US tariff on imported pens (peak)', value: '30%', unit: 'in the 1960s–70s' },
      { label: 'EU REACH restricted substances', value: '200+', unit: 'some found in pen inks/plastics' },
      { label: 'BIC Cristal patent filing', value: '1950', unit: 'design now a protected trademark' },
      { label: 'Countries with pen import restrictions', value: '40+', unit: 'historically or currently' },
      { label: 'FDA food contact regulations', value: 'CFR 21', unit: 'governs ink safety standards' },
    ],
    pullQuote: 'The pen industry was built as much in courtrooms and customs offices as it was in factories.',
    timeline: [
      { year: '1938', event: 'Bíró files ballpoint patent in Hungary — begins decades of licensing disputes' },
      { year: '1945', event: 'Eversharp and Reynolds both claim US rights to ballpoint technology — legal battles begin' },
      { year: '1960s', event: 'US tariffs protect domestic pen manufacturers from cheaper imports' },
      { year: '1976', event: 'CPSC bans certain pen cap designs after children choke — safety regulations tighten' },
      { year: '1994', event: 'ISO 11540 standard for pen cap ventilation published — prevents choking deaths' },
      { year: '2021', event: 'EU Single-Use Plastics Directive pushes pen industry toward refillable designs' },
    ],
  },
];
